name: Test Action in Action from marketplace
on: [workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Run my own container action
        id: the-action
        uses: twhalsema/MyActionInAction@v1.0.0
        with:
          who-to-greet: 'tomtomtom'

      - name: Output the answer from container action
        run: echo "The answer is ${{ steps.the-action.outputs.answer }}"
      
